### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by misterpaul4**
- Made fixes as recommended from previous reviews. 

- Used my_each for loops in other methods. 

- Added multiply_els method to test my_inject method although i wasn't sure if i should remove it or not

- my_map can be tested with procs as well

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @misterpaul4  👋

You've obviously done something here, good job working on my_each method.👍

However, kindly make the following changes:

- [x] my_each is expected to return an enumerator when no block is given, kindly add this functionality.
- [x] Required - Kindly note that as stated in the project specifications on Odin you are required to add the following methods listed in the screenshot below. Refer to the project specification from [Partwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/), here is [the Odin link](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods).
ice_screenshot_20200518-132900


Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by mikenath223** [comment]
In addition, kindly fix your linting errors, you can consider using other looping methods apart from the for-in loop.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @misterpaul4 
### You have done great so far and for also implementing changes from the previous review :clap: However, you have a few issues you need to fix before the project could be approved.
- [x] my_none? did not pass all the test, make sure all the test passes, check the image below for the failed tests
my_none
- [x] my_any? also did not pass all the test cases, check the image below for failed test cases
my_any
- [x] my_all? also did not pass all the test cases, check the image below for failed test cases
my_all
- [x] Also, add multiply_els method and make its test case pass

### Make all these changes and submit for another code review. Good luck.
- Happy coding!

By Raymond
slack @iamraymond

**Comment by lekegitrepo** [comment]
#### Hi @misterpaul4 :clap: :clap:
#### You did a good job :+1: 
#### Add a descriptive readme file and then submit for review.

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by uryelah** [comment]
Hello **Paul Ajuizeogu**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

---------    
    
Good job updating your readme file!

---------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by rOluochKe — COMMENTED** [review]
You submitted a wrong pr for review. Kindly confirm

**Pull request merged**
